### PR TITLE
DeLTA's Segmentation Module

### PR DESCRIPTION
**Pull request by Jamesr787**
This pull request adds the option to segment 2D images with DeLTA (Deep Learning for Time-Lapse Analysis). DeLTA utilizes a U-Net Convolutional Neural Network to segment images. DeLTA has been trained on microscopy images of E. Coli on agar pads and in mother machines. 

__init__.py installs the latest version of DeLTA (delta2)

acdcSegment.py segments and labels 2D images of E. Coli on agar pads or single chambers from mother machines. The first time using the segmentation, it will download the configuration files for 2D (E. Coli on agar pads) and mothermachine. It will also download the weights for the model.  

DeLTA project on GitLab: [https://gitlab.com/dunloplab/delta/](url)

### CODE REVIEW

**Comment by ElpadoCan** [comment]
Hi @Jamesr787, thank you very much for this PR! 

I'm very interested in trying this model out, would you be able to provide a test dataset? Even just two frames will be enough. You should be able to attach files here, but if you don't want them to be public you can send it to my email (or with Google Drive) padovaf@tcd.ie 

The implementation looks very good to me, I have only two comments:

1. If you don't need the `model_type` argument in the `segment` method you can remove it and the parameters in the GUI widget will be empty (which is fine because the user understands that there are no parameters to set).
2. If you want the user to set the parameters of the `delta_preprocess` method you could also add them to the `segment` method. This way they will appear in the GUI widget.

Let me know what you think about it, and if you don't want to change anything it is already good to me and I will proceed to merge this PR. Thanks! 

Cheers,
Francesco

**Comment by Jamesr787** [comment]
Hi Francesco,

I have attached the two images below (one for 2D and one for mothermachine). GitHub only allows JPEG images to be attached here, so let me know if you need the tiff files instead. 

The GUI widget has been giving me an error when I leave it empty. Also, when I include an argument for the tracking module, a widget does not pop up. 

2D_Delta_example

mothermachine_Delta_example

Best,
James

**Comment by ElpadoCan** [comment]
Hi James,

Thank you very much for the images, JPEG should be fine I will let you know.

I will merge your pull request and I will test why you get the error without arguments. I think you might be able to add the `signals=None` keyword argument which is an argument ignored by the GUI widget, but I will let you know as soon as I test.

For the tracking module instead, are you also trying to add a tracker? If so, you could also open a pull request for that and I can test why you don't get the GUI. Let me know, thanks! 

Cheers,
Francesco

**Comment by ElpadoCan** [comment]
Hi @Jamesr787, I had a chance to try out the model and it works really well, nice job! 

I did only two minor changes:

1. I fixed the error when the model has no parameters, so now I removed the `model_type` argument from the `segment` method
2. I added an external function called `url_help()` that returns the gitlab URL. This automatically adds a "See here" text on the GUI widget that user can click and open the gitlab repo. 

Besides this, nice work and enjoy the new model in Cell-ACDC! Feel free to contact me for any other issue or PR! 

Cheers,
Francesco

**Pull request merged**
