### PR TITLE
DeLTA's Tracking Module 

### PR DESCRIPTION
**Pull request by Jamesr787**
This pull request adds the option to track 2D images with DeLTA (Deep Learning for Time-Lapse Analysis).  DeLTA's tracking has been trained on microscopy images of E. Coli on agar pads and in mother machines.

init.py installs the latest version of DeLTA (delta2)

delta_tracker.py tracks and labels 2D images of E. Coli on agar pads or single chambers from mother machines. The first-time using DeLTA, it will download the configuration files for 2D (E. Coli on agar pads) and mothermachine. It will also download the weights for the model.

The class DeltaTrackerParamsWin supplies the user with a window to select different parameters.

Three of the parameters are saving options which will save the results as a .mat, .pkl, or as a movie .mp4. 

DeLTA requires the original images to preform tracking, thus it would be nice if the original images were already supplied as a parameter to the tracker. 

Please let me know if you have any questions or comments! 

Test files can be seen in this google drive:
https://drive.google.com/drive/folders/1SdQdcOGHpxydCdT6qYIUvZf1ODXsGTGE?usp=sharing

Thank you,
James

### CODE REVIEW

**Comment by ElpadoCan** [comment]
Hi @Jamesr787,

I just had a quick look now, I will do some tests on Monday but I can already see that you made a specific widget for delta tracking, amazing job! 

I can test it on some of my yeast data (since it is similar phase contrast), but if you can I would also test it on data more specific to what delta was made for. Would you have a chance to share a small video with me? You can send it via Google Drive to my email padovaf@tcd.ie, thanks! Have a good weekend! 

Cheers,
Francesco

**Comment by Jamesr787** [comment]
Hi Francesco,

Yes! The widget makes it easier to select the original images file.

Please let me know if you have any comments or changes.

best,
James

**Comment by ElpadoCan** [comment]
Hi James, 

I just tested the tracker and it works perfectly, great job! 

Since you mentioned the path to the original images, I decided to modify the `DeltaTrackerParamsWin` widget. Now it should automatically initialize the `modelPathLineEdit` entry to the path of the loaded images. See line `2605-2607` of `apps.DeltaTrackerParamsWin`.

If you are fine with this change I can proceed to merge right away. Let me know, thanks! 

Cheers,
Francesco

PS: What do you think if I add a channel selector to the automatic tracker widget? In your case, you coded the entire widget, but I think it would be nice to have the path to the original images also in the default widget.

**Comment by Jamesr787** [comment]
Hi Francesco,

Thank you for adding the path to the original images as a default! You can merge it!

Yes, I think having a channel selector in the automatic tracker would make it easier for other algorithms to be added that require the original images. 

Thank you! 

Best,
James

**Pull request merged**
